# Generated by Django 5.1.3 on 2024-12-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='timestamp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
