# Generated by Django 5.1.3 on 2024-12-10 07:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('wfo', 'Working Office'), ('wfh', 'Work From Home'), ('leave', 'Leave'), ('abs', 'Absent'), ('fhw', 'First-Half Working'), ('shw', 'Second-Half Working')], default='abs', max_length=100),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='on_leave',
        ),
    ]
