# Generated by Django 5.1.3 on 2024-12-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_unique_together_attendance_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Absent'), (1, 'First-Half Working'), (2, 'Leave'), (3, 'Second-Half Working'), (4, 'Work From Home'), (5, 'Working Office')], default=0, max_length=100),
        ),
    ]
