# Generated by Django 5.1.3 on 2024-12-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Absent'), (1, 'First-Half Working'), (2, 'Leave'), (3, 'Second-Half Working'), (4, 'Work From Home'), (5, 'Working Office')], default=0),
        ),
    ]
