# Generated by Django 5.1.3 on 2024-12-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='attempt',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='attendance',
            name='ip',
            field=models.CharField(default='00.00.00.00', max_length=15),
        ),
    ]
