# Generated by Django 5.1.3 on 2024-12-15 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_attendance_unique_together_attendance_attempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date(2024, 12, 15)),
        ),
    ]
